### PR TITLE
Update to latest torch, add caveats to README, add some small things

### PR DESCRIPTION
**Pull request by Vindaar**
- wraps a few more things:
  - `tanh`, `tanh_mut`
  - `deviceCount`
  - `TensorDataset`, `toDataset`

and updates the torch downloader to get the latest version by default (1.10.2 libtorch with CUDA 11.3).

And add a section in the README about the `{.noInit.}` problems & CUDA support.

### CODE REVIEW

**Review by mratsim — APPROVED** [review]

**Comment by HugoGranstrom** [comment]
> And add a section in the README about the {.noInit.} problems 

This would be outdated now with Nim 2.0 :partying_face:

**Comment by Vindaar** [comment]
Heh, it's really time I finish this now. But only a matter of a bit, because soon I will need to have some git tags for my thesis anyway. :rofl:

**Comment by Clonkk** [comment]
With Nim 2.0 out, the testsuite works.

@Vindaar it's time to merge this :)

**Comment by Vindaar** [comment]
Ah, I once again forgot this still needs to be merged! Let me check if there's still something uncommited locally.

**Comment by Clonkk** [comment]
I finished pushing my local change from last time :).

When it's ok for you and CI is happy let's merge this

**Pull request merged**
