### PR TITLE
Clonkk dev

### PR DESCRIPTION
**Pull request by Clonkk**
* Add std::string related proc 
* Add logspace, linspace, arange, rand, rand_like
* Complete fft proc

### CODE REVIEW

**Comment by Clonkk** [comment]
FYI, @HugoGranstrom I removed some leftover echo in your macro flambeau/high_level/moduleSugar.nim :)

**Comment by Clonkk** [comment]
@mratsim @HugoGranstrom  The repo https://github.com/Clonkk/nim-cppstl got transferred to me (origina lauthor didn't want to maintain it anymore).
 
I was thinking of getting rid of flambeau/cpp/std_cpp and replace it by cppstl. 

What do you think ?

**Comment by mratsim** [comment]
Sounds good to me

**Comment by Clonkk** [comment]
I'll stop here as a "add ftt proc" PR and start new one for the cppstl migrations of C++ STL stuff otherwise it'll get too big

For now I just moved Vector and String which are already existing.

**Comment by HugoGranstrom** [comment]
@Clonkk you have the rights to merge PR yourself now, right?

**Comment by Clonkk** [comment]
Yes, but I wanted to wait a few days and look at it again with a fresh pair of eyes. 

Later we probably need to protect the master branch against merge without review though

**Comment by HugoGranstrom** [comment]
Ok, got you! 😄

Yeah eventually, but that feels quite a long way into the future atm.

**Pull request merged**
