### PR TITLE
fix installing flambeau library in /pkgs properly

### PR DESCRIPTION
**Pull request by Clonkk**
This is a PR to fix and close the installation of flambeau using nimble.

### CODE REVIEW

**Comment by Clonkk** [comment]
@HugoGranstrom This moves the ``install`` folder. Make sure it doesn't conflict what any of your current branch before I merge this.

**Comment by HugoGranstrom** [comment]
All my code is already in master so if it works for you, merge it 😄

**Comment by Clonkk** [comment]
Okay, just be warned you may have conflict in your currently open PR :)

**Comment by HugoGranstrom** [comment]
Oh that one! 🤦 I didn't touch the installation there so it will probably be fine :D

**Pull request merged**
